# -*- coding: utf-8 -*-
"""vision.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LC4URypGkK3bBJrB0FVtIvgJPRmG7Rqg
"""

from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/IFBlend

pip install -r ./requirements.txt

# Commented out IPython magic to ensure Python compatibility.
# %run train.py \
    --model_name ifblend \
    --n_epochs 200 \
    --batch_size 4 \
    --lr 0.0002 \
    --data_src ./data/AMBIENT6K \
    --res_dir ./results \
    --ckp_dir ./checkpoints \
    --description "IFBLEND_exp1" \
    --load 1 \
    --load_from IFBLEND_exp1 \
    --n_cpu 12

#--lr 0.0002->0.0001 at epoch 18 -> at epoch 33 batch size 2->16 -> at epoch 43 lr 0.00005 -> 0.0005로 ㄱㄱ

# Commented out IPython magic to ensure Python compatibility.
# %run eval.py --data_src ./data/AMBIENT6K --ckp_dir ./checkpoints --res_dir ./final-results --load_from IFBlend_ambient6k

